name: Build lac
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0
    - uses: actions/cache@preview
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - uses: cachix/install-nix-action@v11
      with:
        install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-3.0pre20201007_5257a25/install
        nix_path: nixpkgs=channel:nixos-20.09
        extra_nix_config: |
          experimental-features = nix-command flakes
    - uses: cachix/cachix-action@v6
      with:
        name: lorenzleutgeb-public
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix flake check
    - run: "eval \"$(nix print-dev-env)\""
    - run: javac -version
    - run: gradle -version
    - run: wget https://lorenz.leutgeb.xyz/lac/com.microsoft.z3.jar --directory-prefix lib/
    - run: wget https://lorenz.leutgeb.xyz/lac/libz3java.so --directory-prefix lib/
    - run: gradle build -x test
    - run: ./tacas.sh
    - uses: actions/upload-artifact@v2
      with:
        name: tacas
        path: build/distributions/tacas.zip
