name: Build lac
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0
    - name: Cache Nix Store
      uses: actions/cache@v2
      id: cache-nix
      with:
        path: nix-store.nar
        key: nix-${{ runner.os }}-${{ github.sha }}
        restore-keys: |
          nix-${{ runner.os }}-
    - uses: cachix/install-nix-action@v11
      with:
        install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-3.0pre20201007_5257a25/install
        nix_path: nixpkgs=channel:nixos-20.09
        extra_nix_config: |
          experimental-features = nix-command flakes
    - name: Import Nix Store
      if: steps.cache-nix.outputs.cache-hit
      run: nix-store --import < nix-store.nar
    - run: nix flake check
    - run: "eval \"$(nix print-dev-env)\""
    - name: Compute Closure
      run: nix-store --query --references $(nix eval --raw .#defaultPackage.x86_64-linux.drvPath) | xargs nix-store --realise | xargs nix-store --query --requisites | tee closure.txt
    - name: Export Nix Store
      run: xargs --arg-file=closure.txt nix-store --export > nix-store.nar
   #- name: Set up Docker Buildx
   #  uses: docker/setup-buildx-action@v1
    - name: Login to Docker Hub
      uses: docker/login-action@v1.6.0
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1.6.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}
    - name: Load Docker Image from Nix Store
      run: docker load < $(nix path-info .#packages.linux-x86_64.docker-lac)
    - name: Tag Docker Imae for Docker Hub
      run: docker tag lac:latest lorenzleutgeb/lac:${{ github.sha }}
    - name: Push Docker Image to Docker Hub
      run: docker push lorenzleutgeb/lac:${{ github.sha }}
    - name: Tag Docker image for GitHub Packages
      run: docker tag lac:latest ghcr.io/lorenzleutgeb/lac/lac:${{ github.sha }}
    - name: Push Docker Image to GitHub Packages
      run: docker push ghcr.io/lorenzleutgeb/lac/lac:${{ github.sha }}
   #- name: Package TACAS Artifact
   #  run: ./tacas.sh
   #- uses: actions/upload-artifact@v2
   #  with:
   #    name: tacas
   #    path: build/distributions/tacas.zip
    - uses: actions/upload-artifact@v2
      with:
        name: nix
        path: |
          nix-store.nar
          closure.txt
