name: Build lac
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: actions/cache@preview
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - uses: actions/cache@preview
      with:
        path: ~/.stack/programs
        key: ${{ runner.os }}-stack-programs-${{ hashFiles('**/stack.yaml') }}
        restore-keys: |
          ${{ runner.os }}-stack-programs-
    - uses: actions/cache@preview
      with:
        path: interpreter/.stack-work
        key: ${{ runner.os }}-stack-work-${{ hashFiles('**/stack.yaml') }}
        restore-keys: |
          ${{ runner.os }}-stack-work-
    - uses: actions/setup-java@v1
      with:
        java-version: 14
    - run: stack upgrade
    - run: wget https://lorenz.leutgeb.xyz/lac/com.microsoft.z3.jar --directory-prefix typechecker/lib/
    - run: wget https://lorenz.leutgeb.xyz/lac/libz3java.so --directory-prefix typechecker/lib/
    - run: ./gradlew build -x test
      working-directory: typechecker
    - run: stack build
      working-directory: interpreter
    - run: ./tacas.sh
      working-directory: typechecker
    - uses: actions/upload-artifact@v2
      with:
        name: tacas
        path: typechecker/build/distributions/tacas.zip
