name: Build atlas using Gradle
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0
    - uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    - uses: gradle/gradle-build-action@v2
      with:
        gradle-version: '7.3'
        arguments: 'nativeImage jacocoTestReport'
